name: real_estate_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # http: ^0.13.0
  http: ^1.0.0

  fl_chart: ^0.70.2 
  cupertino_icons: ^1.0.8
  video_player: ^2.9.3
  lottie: ^3.3.1
  flutter_screenutil: ^5.9.0
  syncfusion_flutter_charts: ^20.4.49
  image_picker: ^1.0.7
  intl: ^0.18.1
  file_picker: ^5.2.5
  image_preview: ^1.0.3
  audioplayers: ^5.2.1
  badges: ^3.1.2
  flutter_staggered_animations: ^1.0.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  package_info_plus: ^5.0.0
  smooth_page_indicator: ^1.0.0
  flutter_svg: ^1.1.6
  gap: ^3.0.1 
  go_router: ^13.0.1
  flutter_vector_icons: ^2.0.0
  pdf: ^3.9.0
  printing: ^5.9.0
  csv: ^5.0.0
  path_provider: ^2.0.11
  open_file: ^3.2.1
  dio: ^5.8.0+1
  cached_network_image: ^3.3.1
  google_maps_flutter: ^2.5.0
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.1.5
  fluttertoast: ^8.0.9
  
  json_annotation: ^4.8.1
  auto_size_text: ^3.0.0
  



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/avater.webp
    - assets/gifs/intro.mp4
    - assets/images/page1.json
    - assets/images/page2.json
    - assets/images/page3.json
    - assets/images/house.json
    - assets/animations/house.json
    - assets/animations/house2.json
    - assets/animations/house3.json

  
